### ISSUE TITLE
🎷 Podcast Jingle

### ISSUE THREAD

**Issue by benfoxall** [remotehack/remotehack.github.io#59]
It's be really cool if we had some jingle music for the podcast.

### 🎺 Even cooler

If we "built" the instruments ourselves

### 🪕 Maybe even…

A jingle "generator" that could be unique for each episode?

**Comment by lpmi-13** [comment]
I mean...don't get me excited about using the transcript of the previous episode to be run through some sort of seq-2-seq AI model to generate the jingle for the following episode...

**Comment by omgmog** [comment]
Just listening through episode 16 and realised that this has now been sort of solved low-tech since January! 

- [Long version](https://github.com/remotehack/live/blob/master/audio/intro-long.m4a)
- [Short version](https://github.com/remotehack/live/blob/master/audio/intro-short.m4a)

The jingle is based on some royalty free music from https://pixabay.com/music/

**Comment by lpmi-13** [comment]
low tech solved == CLOSED!
